#!/usr/bin/env python3
"""Reusable ROI preprocessing, quality-control, detrending, and PSD utilities.

This module contains the non-Hurst parts of the icy-worlds roughness workflow.
It is imported by ``run_roi_analysis_multibody.py`` and is not intended to be
run directly.

The catalog written by the OpenCV ROI selector stores image coordinates using
zero-based pixel indexing. USGS ISIS ``crop`` uses one-based SAMPLE/LINE start
coordinates, so this module explicitly converts catalog X/Y to ISIS SAMPLE/LINE
when cropping axis-aligned ROIs.

Rotated ROIs are loaded from the selector-created ``Rotated DTM NPY`` file.
That saved array is treated as the frozen science input for exact reproduction.
"""

from __future__ import annotations

import csv
import re
import shutil
import subprocess
from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt
import numpy as np
from scipy.interpolate import griddata
from scipy.ndimage import distance_transform_edt, median_filter


# ---------------------------------------------------------------------------
# Runtime configuration
# ---------------------------------------------------------------------------

ROI_CATALOG = Path("catalogs/roi_catalog.csv")
OUTPUT_ROOT = Path("results/reproducible_rois")
REPO_ROOT = Path.cwd()

NULL_VALUE = -9999
NULL_THRESHOLD = -9000

GOOD_MAX_BAD_FRACTION = 0.01
QUESTIONABLE_MAX_BAD_FRACTION = 0.05
NEEDS_REVIEW_MAX_BAD_FRACTION = 0.10

SKIP_REJECTED_ROIS = True
STOP_IF_LARGE_NULL_REGION = False
MEDIAN_FILTER_SIZE = 3

ALLOW_INTERPOLATION_FOR_REJECTED_ROIS = True
INTERPOLATION_METHOD = "linear_then_nearest"
SAVE_INTERPOLATION_MASK = True

# The multibody OpenCV selector stores image pixel coordinates starting at 0.
# ISIS crop SAMPLE/LINE starts at 1. Do not change this unless your catalog was
# generated by a different tool that already stores one-based ISIS coordinates.
CATALOG_COORDINATES_ARE_ZERO_BASED = True


# ---------------------------------------------------------------------------
# Catalog and path helpers
# ---------------------------------------------------------------------------

def clean_text(value: Any) -> str:
    """Return a safe stripped string for catalog values."""
    return "" if value is None else str(value).strip()


def normalize_catalog_header(header: Any) -> str:
    """Normalize a CSV header for matching historical spelling variants."""
    text = clean_text(header).replace("\ufeff", "")
    text = re.sub(r"\s+", " ", text)
    return re.sub(r"[^a-z0-9]+", "", text.casefold())


CATALOG_HEADER_ALIASES = {
    normalize_catalog_header("ROI_ID"): "ROI_ID",
    normalize_catalog_header("Source CUB"): "Source CUB",
    normalize_catalog_header("Source TIFF"): "Source TIFF",
    normalize_catalog_header("X"): "X",
    normalize_catalog_header("Y"): "Y",
    normalize_catalog_header("Width"): "Width",
    normalize_catalog_header("Height"): "Height",
    normalize_catalog_header("Pixel Scale m/pixel"): "Pixel Scale m/pixel",
    normalize_catalog_header("QC Status"): "QC Status",
    normalize_catalog_header("roi_shape"): "roi_shape",
    normalize_catalog_header("rotation_deg"): "rotation_deg",
    normalize_catalog_header("Display Rotation Degrees"): "Display Rotation Degrees",
    normalize_catalog_header("Rotated Corners Original Image"): "Rotated Corners Original Image",
    normalize_catalog_header("Bounding Box X"): "Bounding Box X",
    normalize_catalog_header("Bounding Box Y"): "Bounding Box Y",
    normalize_catalog_header("Bounding Box Width"): "Bounding Box Width",
    normalize_catalog_header("Bounding Box Height"): "Bounding Box Height",
    normalize_catalog_header("Rotated Width Pixels"): "Rotated Width Pixels",
    normalize_catalog_header("Rotated Height Pixels"): "Rotated Height Pixels",
    normalize_catalog_header("Rotated DTM NPY"): "Rotated DTM NPY",
    normalize_catalog_header("Selected by"): "Selected By",
    normalize_catalog_header("Dsplay Scale"): "Display Scale",
}


def canonical_catalog_header(header: Any) -> str:
    """Return the canonical header name used by the analysis workflow."""
    cleaned = clean_text(header).replace("\ufeff", "")
    return CATALOG_HEADER_ALIASES.get(normalize_catalog_header(cleaned), cleaned)


def resolve_project_path(value: Any, repo_root: Path | None = None) -> Path | None:
    """Resolve an absolute or repository-relative catalog path."""
    text = clean_text(value)
    if not text:
        return None

    path = Path(text).expanduser()
    if path.is_absolute():
        return path

    root = Path(repo_root) if repo_root is not None else REPO_ROOT
    return (root / path).resolve()


def load_roi_catalog_row(roi_id: str) -> dict[str, str]:
    """Load one ROI row while safely handling duplicate legacy headers."""
    if not ROI_CATALOG.exists():
        raise FileNotFoundError(f"Could not find ROI catalog: {ROI_CATALOG}")

    target_id = clean_text(roi_id)
    with ROI_CATALOG.open("r", newline="", encoding="utf-8-sig") as handle:
        rows = list(csv.reader(handle))

    if not rows:
        raise ValueError(f"ROI catalog is empty: {ROI_CATALOG}")

    raw_headers = rows[0]
    for values in rows[1:]:
        row: dict[str, str] = {}

        for index, raw_header in enumerate(raw_headers):
            header = canonical_catalog_header(raw_header)
            if not header:
                continue

            value = clean_text(values[index] if index < len(values) else "")
            if header not in row or (not clean_text(row[header]) and value):
                row[header] = value

        if clean_text(row.get("ROI_ID")) == target_id:
            return row

    raise ValueError(f"ROI_ID not found in catalog: {roi_id}")


def list_roi_ids() -> list[str]:
    """Return nonblank ROI IDs from the configured catalog in file order."""
    if not ROI_CATALOG.exists():
        raise FileNotFoundError(f"Could not find ROI catalog: {ROI_CATALOG}")

    ids: list[str] = []
    with ROI_CATALOG.open("r", newline="", encoding="utf-8-sig") as handle:
        reader = csv.DictReader(handle)
        for raw_row in reader:
            row = {canonical_catalog_header(k): v for k, v in raw_row.items() if k}
            roi_id = clean_text(row.get("ROI_ID"))
            if roi_id and roi_id not in ids:
                ids.append(roi_id)
    return ids


def safe_float(value: Any) -> float | None:
    """Convert a value to float, returning None for blank/unknown values."""
    text = clean_text(value)
    if not text or text.casefold() in {"unknown", "none"}:
        return None
    return float(text)


def safe_optional_int(value: Any) -> int | None:
    """Convert a possibly blank catalog field to int."""
    text = clean_text(value)
    return int(float(text)) if text else None


def first_available_int(*values: Any) -> int | None:
    """Return the first nonblank integer among candidate values."""
    for value in values:
        converted = safe_optional_int(value)
        if converted is not None:
            return converted
    return None


def prepare_roi_geometry_for_analysis(
    row: dict[str, Any],
    repo_root: Path | None = None,
) -> dict[str, Any]:
    """Interpret the axis-aligned-versus-rotated ROI catalog schema."""
    warnings: list[str] = []

    raw_shape = clean_text(row.get("roi_shape")).lower()
    rotated_dtm_npy = clean_text(row.get("Rotated DTM NPY"))

    rotation_deg = safe_float(row.get("rotation_deg"))
    if rotation_deg is None:
        rotation_deg = safe_float(row.get("Display Rotation Degrees"))
    if rotation_deg is None:
        rotation_deg = 0.0

    if not raw_shape:
        if rotated_dtm_npy and abs(rotation_deg) > 1e-6:
            roi_shape = "rotated_rect"
            warnings.append(
                "Legacy row has no roi_shape; inferred rotated_rect from "
                "nonzero rotation plus Rotated DTM NPY."
            )
        else:
            roi_shape = "axis_aligned_rect"
            warnings.append(
                "Legacy row has no roi_shape; treated as axis_aligned_rect."
            )
    elif raw_shape in {"axis_aligned_rect", "rotated_rect"}:
        roi_shape = raw_shape
    else:
        raise ValueError(
            f"Unsupported roi_shape {raw_shape!r}; expected "
            "'axis_aligned_rect' or 'rotated_rect'."
        )

    if roi_shape == "rotated_rect":
        if not rotated_dtm_npy:
            raise ValueError(
                "ROI is rotated_rect but 'Rotated DTM NPY' is blank."
            )

        rotated_dtm_path = resolve_project_path(rotated_dtm_npy, repo_root)
        assert rotated_dtm_path is not None
        if not rotated_dtm_path.exists():
            raise FileNotFoundError(
                f"Rotated science DTM does not exist: {rotated_dtm_path}"
            )

        analysis_width = safe_optional_int(row.get("Rotated Width Pixels"))
        analysis_height = safe_optional_int(row.get("Rotated Height Pixels"))
        if analysis_width is None or analysis_height is None:
            raise ValueError(
                "rotated_rect requires Rotated Width Pixels and "
                "Rotated Height Pixels."
            )

        bbox_x = first_available_int(row.get("Bounding Box X"), row.get("X"))
        bbox_y = first_available_int(row.get("Bounding Box Y"), row.get("Y"))
        bbox_width = first_available_int(
            row.get("Bounding Box Width"), row.get("Width")
        )
        bbox_height = first_available_int(
            row.get("Bounding Box Height"), row.get("Height")
        )

        if abs(rotation_deg) <= 1e-6:
            warnings.append(
                "roi_shape is rotated_rect but rotation is zero/blank; "
                "the explicit rotated .npy remains the science input."
            )

        return {
            "roi_shape": roi_shape,
            "rotation_deg": float(rotation_deg),
            "input_mode": "pre_extracted_rotated_npy",
            "is_rotated_roi": True,
            "analysis_width_pixels": int(analysis_width),
            "analysis_height_pixels": int(analysis_height),
            "rotated_dtm_npy": str(rotated_dtm_path),
            "catalog_crop_x": bbox_x,
            "catalog_crop_y": bbox_y,
            "catalog_crop_width": bbox_width,
            "catalog_crop_height": bbox_height,
            "warnings": warnings,
        }

    x = safe_optional_int(row.get("X"))
    y = safe_optional_int(row.get("Y"))
    width = safe_optional_int(row.get("Width"))
    height = safe_optional_int(row.get("Height"))

    missing = [
        name
        for name, value in {
            "X": x,
            "Y": y,
            "Width": width,
            "Height": height,
        }.items()
        if value is None
    ]
    if missing:
        raise ValueError(
            "axis_aligned_rect is missing required crop fields: "
            + ", ".join(missing)
        )

    if rotated_dtm_npy:
        warnings.append(
            "Axis-aligned ROI contains a Rotated DTM NPY; it is ignored."
        )

    rotated_metadata_present = any(
        clean_text(row.get(field))
        for field in (
            "Rotated Corners Original Image",
            "Bounding Box X",
            "Bounding Box Y",
            "Bounding Box Width",
            "Bounding Box Height",
            "Rotated Width Pixels",
            "Rotated Height Pixels",
        )
    )
    if rotated_metadata_present:
        warnings.append(
            "Axis-aligned ROI contains rotated metadata; those fields are "
            "ignored for analysis."
        )

    if abs(rotation_deg) > 1e-6:
        warnings.append(
            "Axis-aligned ROI has a nonzero catalog rotation; roi_shape takes "
            "precedence and the ROI is analyzed as axis-aligned."
        )

    return {
        "roi_shape": roi_shape,
        "rotation_deg": float(rotation_deg),
        "input_mode": "isis_cub_crop_ascii",
        "is_rotated_roi": False,
        "analysis_width_pixels": int(width),
        "analysis_height_pixels": int(height),
        "rotated_dtm_npy": "",
        "catalog_crop_x": int(x),
        "catalog_crop_y": int(y),
        "catalog_crop_width": int(width),
        "catalog_crop_height": int(height),
        "warnings": warnings,
    }


# ---------------------------------------------------------------------------
# ISIS extraction
# ---------------------------------------------------------------------------

def make_roi_folders(roi_id: str) -> tuple[Path, Path, Path, Path]:
    """Create the standard per-ROI output folders."""
    roi_dir = OUTPUT_ROOT / roi_id
    data_dir = roi_dir / "data"
    figure_dir = roi_dir / "figures"
    log_dir = roi_dir / "logs"

    for directory in (data_dir, figure_dir, log_dir):
        directory.mkdir(parents=True, exist_ok=True)

    return roi_dir, data_dir, figure_dir, log_dir


def _require_executable(name: str) -> None:
    if shutil.which(name) is None:
        raise RuntimeError(
            f"Required USGS ISIS executable {name!r} was not found on PATH. "
            "Activate the ISIS environment before running axis-aligned ROIs."
        )


def run_command(command: list[Any], log_lines: list[str]) -> subprocess.CompletedProcess[str]:
    """Run an external command and append command/stdout/stderr to the log."""
    executable = str(command[0])
    _require_executable(executable)

    command_text = " ".join(str(part) for part in command)
    log_lines.append(f"\nCOMMAND:\n{command_text}\n")

    result = subprocess.run(
        [str(part) for part in command],
        capture_output=True,
        text=True,
        check=False,
    )

    log_lines.append("STDOUT:\n" + result.stdout)
    log_lines.append("STDERR:\n" + result.stderr)

    if result.returncode != 0:
        raise RuntimeError(
            f"Command failed with return code {result.returncode}:\n"
            f"{command_text}\n\nSTDOUT:\n{result.stdout}\n\n"
            f"STDERR:\n{result.stderr}"
        )

    return result


def catalog_xy_to_isis_sample_line(x: int, y: int) -> tuple[int, int]:
    """Convert selector catalog X/Y to ISIS SAMPLE/LINE starts."""
    if CATALOG_COORDINATES_ARE_ZERO_BASED:
        return int(x) + 1, int(y) + 1
    return int(x), int(y)


def crop_cub_with_isis(
    source_cub: Path,
    output_cub: Path,
    x: int,
    y: int,
    width: int,
    height: int,
    log_lines: list[str],
) -> None:
    """Crop a CUB using catalog geometry and explicit coordinate conversion."""
    sample, line = catalog_xy_to_isis_sample_line(x, y)
    log_lines.append(
        "Catalog-to-ISIS coordinate conversion: "
        f"X={x}, Y={y} -> SAMPLE={sample}, LINE={line}; "
        f"zero_based_catalog={CATALOG_COORDINATES_ARE_ZERO_BASED}"
    )

    command = [
        "crop",
        f"from={source_cub}",
        f"to={output_cub}",
        f"SAMPLE={sample}",
        f"LINE={line}",
        f"NSAMPLES={int(width)}",
        f"NLINES={int(height)}",
    ]
    run_command(command, log_lines)


def cub_to_ascii_with_isis(
    input_cub: Path,
    output_txt: Path,
    log_lines: list[str],
) -> None:
    """Convert a cropped ISIS CUB to an ASCII elevation grid."""
    command = [
        "isis2ascii",
        f"from={input_cub}",
        f"to={output_txt}",
        "HEADER=false",
        "SETPIXELVALUE=true",
        f"NULLVALUE={NULL_VALUE}",
    ]
    run_command(command, log_lines)


def load_ascii_dtm(txt_path: Path) -> np.ndarray:
    """Load an ISIS ASCII elevation grid into NumPy."""
    return np.loadtxt(txt_path)


def load_raw_dtm_for_roi(
    geometry: dict[str, Any],
    source_cub_path: Path | None,
    cropped_cub: Path,
    ascii_txt: Path,
    raw_dtm_path: Path,
    log_lines: list[str],
) -> tuple[np.ndarray, dict[str, Any]]:
    """Load the science DTM for either an axis-aligned or rotated ROI."""
    if geometry["is_rotated_roi"]:
        rotated_dtm_path = Path(geometry["rotated_dtm_npy"])
        log_lines.extend(
            [
                "\nRAW DTM SOURCE",
                "Using selector-created rotated science DTM.",
                f"Rotated DTM NPY: {rotated_dtm_path}",
            ]
        )

        raw_dtm = np.load(rotated_dtm_path)
        if raw_dtm.ndim != 2:
            raise ValueError(
                f"Rotated DTM must be 2D; got shape {raw_dtm.shape}."
            )

        expected_shape = (
            int(geometry["analysis_height_pixels"]),
            int(geometry["analysis_width_pixels"]),
        )
        if tuple(raw_dtm.shape) != expected_shape:
            raise ValueError(
                "Rotated DTM shape does not match catalog dimensions.\n"
                f"Expected (height, width): {expected_shape}\n"
                f"Loaded: {tuple(raw_dtm.shape)}\n"
                f"Path: {rotated_dtm_path}"
            )

        np.save(raw_dtm_path, raw_dtm)
        return raw_dtm, {
            "raw_dtm_source": "pre_extracted_rotated_npy",
            "input_mode": geometry["input_mode"],
            "roi_shape": geometry["roi_shape"],
            "rotation_deg": geometry["rotation_deg"],
            "rotated_dtm_npy": str(rotated_dtm_path),
            "used_cub_crop": False,
            "expected_shape_height_width": list(expected_shape),
        }

    if source_cub_path is None:
        raise ValueError("axis_aligned_rect requires a Source CUB.")

    log_lines.extend(
        [
            "\nRAW DTM SOURCE",
            "Using axis-aligned CUB crop workflow.",
            "Rotated DTM NPY is not used.",
        ]
    )

    crop_cub_with_isis(
        source_cub_path,
        cropped_cub,
        geometry["catalog_crop_x"],
        geometry["catalog_crop_y"],
        geometry["catalog_crop_width"],
        geometry["catalog_crop_height"],
        log_lines,
    )
    cub_to_ascii_with_isis(cropped_cub, ascii_txt, log_lines)

    raw_dtm = load_ascii_dtm(ascii_txt)
    if raw_dtm.ndim != 2:
        raise ValueError(
            f"Axis-aligned CUB crop must be 2D; got {raw_dtm.shape}."
        )

    expected_shape = (
        int(geometry["analysis_height_pixels"]),
        int(geometry["analysis_width_pixels"]),
    )
    if tuple(raw_dtm.shape) != expected_shape:
        log_lines.append(
            "WARNING: ISIS crop array shape differs from catalog geometry. "
            f"Expected {expected_shape}, loaded {tuple(raw_dtm.shape)}."
        )

    np.save(raw_dtm_path, raw_dtm)
    return raw_dtm, {
        "raw_dtm_source": "isis_cub_crop_ascii",
        "input_mode": geometry["input_mode"],
        "roi_shape": geometry["roi_shape"],
        "rotation_deg": geometry["rotation_deg"],
        "rotated_dtm_npy": "",
        "used_cub_crop": True,
        "source_cub": str(source_cub_path),
        "cropped_cub": str(cropped_cub),
        "ascii_txt": str(ascii_txt),
        "catalog_coordinates_zero_based": CATALOG_COORDINATES_ARE_ZERO_BASED,
        "expected_shape_height_width": list(expected_shape),
        "loaded_shape_height_width": list(raw_dtm.shape),
    }


# ---------------------------------------------------------------------------
# Quality control and cleaning
# ---------------------------------------------------------------------------

def evaluate_raw_dtm_quality(raw_dtm: np.ndarray) -> dict[str, Any]:
    """Evaluate missing/null pixels in a raw DTM."""
    null_mask = (~np.isfinite(raw_dtm)) | (raw_dtm <= NULL_THRESHOLD)

    bad_pixel_count = int(null_mask.sum())
    total_pixel_count = int(raw_dtm.size)
    if total_pixel_count == 0:
        raise ValueError("Raw DTM contains zero pixels.")

    bad_pixel_fraction = bad_pixel_count / total_pixel_count
    row_null_fraction = null_mask.mean(axis=1)
    col_null_fraction = null_mask.mean(axis=0)

    large_null_region = bool(
        row_null_fraction.max() > 0.5 or col_null_fraction.max() > 0.5
    )

    if large_null_region:
        qc_status = "Reject"
        qc_notes = (
            "Large contiguous null-data region detected. "
            "Reselect away from the DTM coverage boundary."
        )
    elif bad_pixel_fraction < GOOD_MAX_BAD_FRACTION:
        qc_status = "Good"
        qc_notes = "Very low bad-pixel fraction."
    elif bad_pixel_fraction < QUESTIONABLE_MAX_BAD_FRACTION:
        qc_status = "Questionable"
        qc_notes = "Small bad-pixel fraction; usable with caution."
    elif bad_pixel_fraction < NEEDS_REVIEW_MAX_BAD_FRACTION:
        qc_status = "Needs Review"
        qc_notes = "Moderate bad-pixel fraction; inspect before final use."
    else:
        qc_status = "Reject"
        qc_notes = "Bad-pixel fraction is too high."

    return {
        "bad_pixel_count": bad_pixel_count,
        "total_pixel_count": total_pixel_count,
        "bad_pixel_fraction": bad_pixel_fraction,
        "large_null_region": large_null_region,
        "qc_status": qc_status,
        "qc_notes": qc_notes,
    }


def clean_dtm_with_median_filter(
    raw_dtm: np.ndarray,
    qc_info: dict[str, Any],
) -> tuple[np.ndarray, dict[str, Any]]:
    """Fill small isolated null pixels using a local median-filter estimate."""
    dtm = raw_dtm.astype(np.float64).copy()
    bad_mask = (~np.isfinite(dtm)) | (dtm <= NULL_THRESHOLD)

    if bad_mask.sum() == 0:
        return dtm, {
            "cleaning_method": "none",
            "cleaning_notes": "No null pixels found.",
        }

    if qc_info["bad_pixel_fraction"] >= NEEDS_REVIEW_MAX_BAD_FRACTION:
        raise ValueError(
            "Bad-pixel fraction is too high for the small-gap median-filter "
            "cleaning path."
        )

    valid_values = dtm[~bad_mask & np.isfinite(dtm)]
    if valid_values.size == 0:
        raise ValueError("No valid pixels found in raw DTM.")

    dtm_for_filter = dtm.copy()
    dtm_for_filter[bad_mask] = np.median(valid_values)
    filtered = median_filter(dtm_for_filter, size=MEDIAN_FILTER_SIZE)

    cleaned = dtm.copy()
    cleaned[bad_mask] = filtered[bad_mask]

    return cleaned, {
        "cleaning_method": "median_filter",
        "median_filter_size": MEDIAN_FILTER_SIZE,
        "cleaning_notes": (
            "Null pixels were replaced with local median-filtered values. "
            "This path is intended for small isolated gaps."
        ),
    }


def interpolate_missing_pixels(
    raw_dtm: np.ndarray,
    qc_info: dict[str, Any],
    method: str = "linear_then_nearest",
) -> tuple[np.ndarray, np.ndarray, dict[str, Any]]:
    """Interpolate missing pixels while preserving an explicit interpolation mask."""
    del qc_info  # retained in the signature for compatibility/provenance

    dtm = raw_dtm.astype(np.float64).copy()
    bad_mask = (~np.isfinite(dtm)) | (dtm <= NULL_THRESHOLD)
    good_mask = ~bad_mask & np.isfinite(dtm)

    bad_pixel_count = int(bad_mask.sum())
    total_pixel_count = int(dtm.size)

    if bad_pixel_count == 0:
        return dtm, bad_mask, {
            "cleaning_method": "none",
            "interpolation_method": None,
            "interpolated_pixel_count": 0,
            "interpolated_fraction": 0.0,
            "cleaning_notes": "No null pixels found.",
        }

    if good_mask.sum() == 0:
        raise ValueError("Cannot interpolate because no valid pixels exist.")

    y_grid, x_grid = np.indices(dtm.shape)
    good_points = np.column_stack((x_grid[good_mask], y_grid[good_mask]))
    good_values = dtm[good_mask]
    bad_points = np.column_stack((x_grid[bad_mask], y_grid[bad_mask]))

    cleaned = dtm.copy()

    if method == "nearest":
        values = griddata(good_points, good_values, bad_points, method="nearest")
        cleaned[bad_mask] = values

    elif method == "linear_then_nearest":
        linear_values = griddata(
            good_points, good_values, bad_points, method="linear"
        )
        nearest_values = griddata(
            good_points, good_values, bad_points, method="nearest"
        )
        final_values = linear_values.copy()
        missing_linear = ~np.isfinite(final_values)
        final_values[missing_linear] = nearest_values[missing_linear]
        cleaned[bad_mask] = final_values

    elif method == "nearest_then_median":
        nearest_values = griddata(
            good_points, good_values, bad_points, method="nearest"
        )
        cleaned[bad_mask] = nearest_values
        smoothed = median_filter(cleaned, size=MEDIAN_FILTER_SIZE)
        cleaned[bad_mask] = smoothed[bad_mask]

    else:
        raise ValueError(f"Unknown interpolation method: {method}")

    if not np.all(np.isfinite(cleaned[bad_mask])):
        raise ValueError(
            "Interpolation left non-finite values in previously missing pixels."
        )

    distance_to_valid = distance_transform_edt(bad_mask)
    distances = distance_to_valid[bad_mask]

    return cleaned, bad_mask, {
        "cleaning_method": "interpolation",
        "interpolation_method": method,
        "interpolated_pixel_count": bad_pixel_count,
        "total_pixel_count": total_pixel_count,
        "interpolated_fraction": bad_pixel_count / total_pixel_count,
        "max_interpolation_distance_pixels": float(distances.max()),
        "mean_interpolation_distance_pixels": float(distances.mean()),
        "mentor_approved_interpolation": True,
        "cleaning_notes": (
            "Missing pixels were interpolated. Interpolation can suppress "
            "roughness and alter PSD/breakpoint behavior, so these ROIs should "
            "be interpreted cautiously."
        ),
    }


# ---------------------------------------------------------------------------
# Detrending and PSD
# ---------------------------------------------------------------------------

def detrend_plane(dtm: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Fit and subtract a least-squares best-fit plane."""
    ny, nx = dtm.shape
    x, y = np.meshgrid(np.arange(nx), np.arange(ny))

    design = np.column_stack(
        (x.ravel(), y.ravel(), np.ones(nx * ny))
    )
    z = dtm.ravel()

    coeffs, _, _, _ = np.linalg.lstsq(design, z, rcond=None)
    plane = coeffs[0] * x + coeffs[1] * y + coeffs[2]
    return dtm - plane, plane, coeffs


def power_spectrum_1d(
    dtm: np.ndarray,
    pixel_scale: float,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Compute a 2D FFT power spectrum and an integer-radius 1D radial average."""
    dtm_zero_mean = dtm - np.mean(dtm)

    fft = np.fft.fft2(dtm_zero_mean)
    fft_shifted = np.fft.fftshift(fft)
    power_2d = np.abs(fft_shifted) ** 2

    ny, nx = dtm.shape
    cy, cx = ny // 2, nx // 2
    y, x = np.indices((ny, nx))
    radius = np.sqrt((x - cx) ** 2 + (y - cy) ** 2).astype(int)

    radial_power = np.bincount(radius.ravel(), power_2d.ravel())
    radial_count = np.bincount(radius.ravel())
    psd_1d = radial_power / np.maximum(radial_count, 1)

    freqs = np.fft.fftfreq(nx, d=pixel_scale)
    if len(freqs) < 2:
        raise ValueError("DTM is too narrow to compute a 1D PSD frequency step.")

    freq_step = abs(freqs[1] - freqs[0])
    radial_freq = np.arange(len(psd_1d)) * freq_step
    return radial_freq[1:], psd_1d[1:], power_2d


# ---------------------------------------------------------------------------
# Plotting
# ---------------------------------------------------------------------------

def save_dtm_preview(dtm: np.ndarray, output_path: Path, title: str) -> None:
    """Save a grayscale DTM preview."""
    fig, ax = plt.subplots(figsize=(7, 6))
    image = ax.imshow(dtm, cmap="gray")
    fig.colorbar(image, ax=ax, label="Elevation / relative height")
    ax.set_title(title)
    ax.set_xlabel("X pixel")
    ax.set_ylabel("Y pixel")
    fig.tight_layout()
    fig.savefig(output_path, dpi=300)
    plt.close(fig)


def save_dtm_preview_mask_nulls(
    dtm: np.ndarray,
    output_path: Path,
    title: str,
) -> None:
    """Save a DTM preview with null values masked."""
    dtm_plot = dtm.astype(float).copy()
    dtm_plot[(~np.isfinite(dtm_plot)) | (dtm_plot <= NULL_THRESHOLD)] = np.nan

    fig, ax = plt.subplots(figsize=(7, 6))
    image = ax.imshow(dtm_plot, cmap="gray")
    fig.colorbar(image, ax=ax, label="Elevation / relative height")
    ax.set_title(title)
    ax.set_xlabel("X pixel")
    ax.set_ylabel("Y pixel")
    fig.tight_layout()
    fig.savefig(output_path, dpi=300)
    plt.close(fig)


def save_null_mask(dtm: np.ndarray, output_path: Path, title: str) -> None:
    """Save the raw-DTM null mask."""
    null_mask = (~np.isfinite(dtm)) | (dtm <= NULL_THRESHOLD)
    fig, ax = plt.subplots(figsize=(7, 6))
    ax.imshow(null_mask, cmap="gray")
    ax.set_title(title)
    ax.set_xlabel("X pixel")
    ax.set_ylabel("Y pixel")
    fig.tight_layout()
    fig.savefig(output_path, dpi=300)
    plt.close(fig)


def save_psd_diagnostic_multipanel_plot(
    dtm: np.ndarray,
    pixel_scale_m: float,
    output_path: Path,
    title: str,
    max_display_percentile: float = 99.0,
) -> None:
    """Save DTM, 2D FFT power, and radially averaged PSD diagnostics."""
    dtm = np.asarray(dtm, dtype=float)
    finite_mask = np.isfinite(dtm)
    if not np.any(finite_mask):
        raise ValueError("DTM has no finite values for PSD diagnostic plot.")

    dtm_clean = dtm.copy()
    dtm_clean[~finite_mask] = np.nanmedian(dtm_clean[finite_mask])
    dtm_zero_mean = dtm_clean - np.mean(dtm_clean)

    nrows, ncols = dtm_zero_mean.shape
    fft_2d = np.fft.fftshift(np.fft.fft2(dtm_zero_mean))
    power_2d = np.abs(fft_2d) ** 2
    power_display = np.log10(power_2d + 1e-12)

    freq_y = np.fft.fftshift(np.fft.fftfreq(nrows, d=pixel_scale_m))
    freq_x = np.fft.fftshift(np.fft.fftfreq(ncols, d=pixel_scale_m))
    fx, fy = np.meshgrid(freq_x, freq_y)
    radial_frequency = np.sqrt(fx**2 + fy**2).ravel()
    power_flat = power_2d.ravel()

    valid = (
        np.isfinite(radial_frequency)
        & np.isfinite(power_flat)
        & (radial_frequency > 0)
        & (power_flat > 0)
    )
    radial_frequency = radial_frequency[valid]
    power_flat = power_flat[valid]

    if radial_frequency.size == 0:
        raise ValueError("No valid positive frequencies for PSD diagnostic.")

    n_bins = 80
    freq_bins = np.logspace(
        np.log10(radial_frequency.min()),
        np.log10(radial_frequency.max()),
        n_bins + 1,
    )
    freq_centers = np.sqrt(freq_bins[:-1] * freq_bins[1:])
    psd_1d = np.full(n_bins, np.nan)
    counts = np.zeros(n_bins, dtype=int)

    for index in range(n_bins):
        in_bin = (
            (radial_frequency >= freq_bins[index])
            & (radial_frequency < freq_bins[index + 1])
        )
        counts[index] = np.count_nonzero(in_bin)
        if counts[index] > 0:
            psd_1d[index] = np.mean(power_flat[in_bin])

    valid_1d = np.isfinite(psd_1d) & (psd_1d > 0) & (counts > 0)

    fig, axes = plt.subplots(1, 3, figsize=(15, 4.8))

    vmin = np.nanpercentile(dtm_clean, 100 - max_display_percentile)
    vmax = np.nanpercentile(dtm_clean, max_display_percentile)
    im0 = axes[0].imshow(
        dtm_clean, origin="upper", cmap="gray", vmin=vmin, vmax=vmax
    )
    axes[0].set_title("Detrended DTM")
    axes[0].set_xlabel("Sample")
    axes[0].set_ylabel("Line")
    fig.colorbar(im0, ax=axes[0], fraction=0.046, pad=0.04).set_label(
        "Elevation residual (m)"
    )

    im1 = axes[1].imshow(power_display, origin="upper", cmap="viridis")
    axes[1].set_title("2D Power Spectrum")
    axes[1].set_xlabel("Frequency x")
    axes[1].set_ylabel("Frequency y")
    fig.colorbar(im1, ax=axes[1], fraction=0.046, pad=0.04).set_label(
        "log10(Power)"
    )

    axes[2].loglog(freq_centers[valid_1d], psd_1d[valid_1d], "-", linewidth=1.8)
    axes[2].set_title("1D Radially Averaged PSD")
    axes[2].set_xlabel("Spatial frequency (1/m)")
    axes[2].set_ylabel("Power")
    axes[2].grid(True, which="both", alpha=0.3)

    fig.suptitle(title, fontsize=14)
    fig.tight_layout()
    fig.savefig(output_path, dpi=300)
    plt.close(fig)


def save_psd_plot(
    freqs: np.ndarray,
    psd: np.ndarray,
    output_path: Path,
    title: str,
) -> None:
    """Save the 1D PSD plot."""
    valid = (freqs > 0) & (psd > 0) & np.isfinite(freqs) & np.isfinite(psd)
    fig, ax = plt.subplots(figsize=(7, 5))
    ax.loglog(freqs[valid], psd[valid])
    ax.set_xlabel("Spatial frequency (1/m)")
    ax.set_ylabel("Power")
    ax.set_title(title)
    fig.tight_layout()
    fig.savefig(output_path, dpi=300)
    plt.close(fig)
